import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./components/Footer";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex flex-col min-h-screen bg-[var(--primary-light)]`}
      >
        <div className="absolute h-full w-full sunburst-bg-half -z-10" />
        <Header />
        {children}
        <Footer />
        {/* <div className="absolute left-1/2 bottom-0 -translate-x-1/2 translate-y-1/2 sunburst-bg-animated -z-10" /> */}
      </body>
    </html>
  );
}
