import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./components/Footer";
import { Header } from "./components/Header";
import { evogria } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`antialiased flex flex-col min-h-screen bg-[var(--primary-light)] overflow-hidden`}
      >
        {/* <div className="absolute h-full w-full sunburst-bg-half -z-10" /> */}
        <Header />
        <main
          className={`${evogria.className} flex flex-col flex-grow justify-center items-center h-full w-9/10 md:w-[980px] mx-auto rounded-t-md gap-10 md:px-10`}
        >
          {children}
        </main>
        <Footer />
        <div className="fixed left-1/2 bottom-0 -translate-x-1/2 translate-y-1/2 sunburst-bg-animated -z-10" />
      </body>
    </html>
  );
}
