export const comunasFallback = [
  { ComunaId: 1, Nombre: "ALGARROBO" },
  { ComunaId: 2, Nombre: "ALHUE" },
  { ComunaId: 3, Nombre: "ALTO BIOBIO" },
  { ComunaId: 4, Nombre: "ALTO DEL CARMEN" },
  { ComunaId: 5, Nombre: "ALTO HOSPICIO" },
  { ComunaId: 6, Nombre: "ANCUD" },
  { ComunaId: 7, Nombre: "ANDACOLLO" },
  { ComunaId: 8, Nombre: "ANGOL" },
  { ComunaId: 9, Nombre: "ANTOFAGASTA" },
  { ComunaId: 10, Nombre: "ANTUCO" },
  { ComunaId: 11, Nombre: "ARAUCO" },
  { ComunaId: 12, Nombre: "ARICA" },
  { ComunaId: 13, Nombre: "AYSEN" },
  { ComunaId: 14, Nombre: "BUIN" },
  { ComunaId: 15, Nombre: "BULNES" },
  { ComunaId: 16, Nombre: "CABILDO" },
  { ComunaId: 17, Nombre: "CABO DE HORNOS" },
  { ComunaId: 18, Nombre: "CABRERO" },
  { ComunaId: 19, Nombre: "CALAMA" },
  { ComunaId: 20, Nombre: "CALBUCO" },
  { ComunaId: 21, Nombre: "CALDERA" },
  { ComunaId: 22, Nombre: "CALERA DE TANGO" },
  { ComunaId: 23, Nombre: "CALLE LARGA" },
  { ComunaId: 24, Nombre: "CAMARONES" },
  { ComunaId: 25, Nombre: "CAMINA" },
  { ComunaId: 26, Nombre: "CANELA" },
  { ComunaId: 27, Nombre: "CANETE" },
  { ComunaId: 28, Nombre: "CARAHUE" },
  { ComunaId: 29, Nombre: "CARTAGENA" },
  { ComunaId: 30, Nombre: "CASABLANCA" },
  { ComunaId: 31, Nombre: "CASTRO" },
  { ComunaId: 32, Nombre: "CATEMU" },
  { ComunaId: 33, Nombre: "CAUQUENES" },
  { ComunaId: 34, Nombre: "CERRILLOS" },
  { ComunaId: 35, Nombre: "CERRO NAVIA" },
  { ComunaId: 36, Nombre: "CHAITEN" },
  { ComunaId: 37, Nombre: "CHANARAL" },
  { ComunaId: 38, Nombre: "CHANCO" },
  { ComunaId: 39, Nombre: "CHEPICA" },
  { ComunaId: 40, Nombre: "CHIGUAYANTE" },
  { ComunaId: 41, Nombre: "CHILE CHICO" },
  { ComunaId: 42, Nombre: "CHILLAN" },
  { ComunaId: 43, Nombre: "CHILLAN VIEJO" },
  { ComunaId: 44, Nombre: "CHIMBARONGO" },
  { ComunaId: 45, Nombre: "CHOLCHOL" },
  { ComunaId: 46, Nombre: "CHONCHI" },
  { ComunaId: 47, Nombre: "CISNES" },
  { ComunaId: 48, Nombre: "COBQUECURA" },
  { ComunaId: 49, Nombre: "COCHAMO" },
  { ComunaId: 50, Nombre: "COCHRANE" },
  { ComunaId: 51, Nombre: "CODEGUA" },
  { ComunaId: 52, Nombre: "COELEMU" },
  { ComunaId: 53, Nombre: "COIHUECO" },
  { ComunaId: 54, Nombre: "COINCO" },
  { ComunaId: 55, Nombre: "COLBUN" },
  { ComunaId: 56, Nombre: "COLCHANE" },
  { ComunaId: 57, Nombre: "COLINA" },
  { ComunaId: 58, Nombre: "COLLIPULLI" },
  { ComunaId: 59, Nombre: "COLTAUCO" },
  { ComunaId: 60, Nombre: "COMBARBALA" },
  { ComunaId: 61, Nombre: "CONCEPCION" },
  { ComunaId: 62, Nombre: "CONCHALI" },
  { ComunaId: 63, Nombre: "CONCON" },
  { ComunaId: 64, Nombre: "CONSTITUCION" },
  { ComunaId: 65, Nombre: "CONTULMO" },
  { ComunaId: 66, Nombre: "COPIAPO" },
  { ComunaId: 67, Nombre: "COQUIMBO" },
  { ComunaId: 68, Nombre: "CORONEL" },
  { ComunaId: 69, Nombre: "CORRAL" },
  { ComunaId: 70, Nombre: "COYHAIQUE" },
  { ComunaId: 71, Nombre: "CUNCO" },
  { ComunaId: 72, Nombre: "CURACAUTIN" },
  { ComunaId: 73, Nombre: "CURACAVI" },
  { ComunaId: 74, Nombre: "CURACO DE VELEZ" },
  { ComunaId: 75, Nombre: "CURANILAHUE" },
  { ComunaId: 76, Nombre: "CURARREHUE" },
  { ComunaId: 77, Nombre: "CUREPTO" },
  { ComunaId: 78, Nombre: "CURICO" },
  { ComunaId: 79, Nombre: "DALCAHUE" },
  { ComunaId: 80, Nombre: "DIEGO DE ALMAGRO" },
  { ComunaId: 81, Nombre: "DONIHUE" },
  { ComunaId: 82, Nombre: "EL BOSQUE" },
  { ComunaId: 83, Nombre: "EL CARMEN" },
  { ComunaId: 84, Nombre: "EL MONTE" },
  { ComunaId: 85, Nombre: "EL QUISCO" },
  { ComunaId: 86, Nombre: "EL TABO" },
  { ComunaId: 87, Nombre: "EMPEDRADO" },
  { ComunaId: 88, Nombre: "ERCILLA" },
  { ComunaId: 89, Nombre: "ESTACION CENTRAL" },
  { ComunaId: 90, Nombre: "FLORIDA" },
  { ComunaId: 91, Nombre: "FREIRE" },
  { ComunaId: 92, Nombre: "FREIRINA" },
  { ComunaId: 93, Nombre: "FRESIA" },
  { ComunaId: 94, Nombre: "FRUTILLAR" },
  { ComunaId: 95, Nombre: "FUTALEUFU" },
  { ComunaId: 96, Nombre: "FUTRONO" },
  { ComunaId: 97, Nombre: "GALVARINO" },
  { ComunaId: 98, Nombre: "GENERAL LAGOS" },
  { ComunaId: 99, Nombre: "GORBEA" },
  { ComunaId: 100, Nombre: "GRANEROS" },
  { ComunaId: 101, Nombre: "GUAITECAS" },
  { ComunaId: 102, Nombre: "HIJUELAS" },
  { ComunaId: 103, Nombre: "HUALAIHUE" },
  { ComunaId: 104, Nombre: "HUALANE" },
  { ComunaId: 105, Nombre: "HUALPEN" },
  { ComunaId: 106, Nombre: "HUALQUI" },
  { ComunaId: 107, Nombre: "HUARA" },
  { ComunaId: 108, Nombre: "HUASCO" },
  { ComunaId: 109, Nombre: "HUECHURABA" },
  { ComunaId: 110, Nombre: "ILLAPEL" },
  { ComunaId: 111, Nombre: "INDEPENDENCIA" },
  { ComunaId: 112, Nombre: "IQUIQUE" },
  { ComunaId: 113, Nombre: "ISLA DE MAIPO" },
  { ComunaId: 114, Nombre: "ISLA DE PASCUA" },
  { ComunaId: 115, Nombre: "JUAN FERNANDEZ" },
  { ComunaId: 116, Nombre: "LA CALERA" },
  { ComunaId: 117, Nombre: "LA CISTERNA" },
  { ComunaId: 118, Nombre: "LA CRUZ" },
  { ComunaId: 119, Nombre: "LA ESTRELLA" },
  { ComunaId: 120, Nombre: "LA FLORIDA" },
  { ComunaId: 121, Nombre: "LA GRANJA" },
  { ComunaId: 122, Nombre: "LA HIGUERA" },
  { ComunaId: 123, Nombre: "LA LIGUA" },
  { ComunaId: 124, Nombre: "LA PINTANA" },
  { ComunaId: 125, Nombre: "LA REINA" },
  { ComunaId: 126, Nombre: "LA SERENA" },
  { ComunaId: 127, Nombre: "LA UNION" },
  { ComunaId: 128, Nombre: "LAGO RANCO" },
  { ComunaId: 129, Nombre: "LAGO VERDE" },
  { ComunaId: 130, Nombre: "LAGUNA BLANCA" },
  { ComunaId: 131, Nombre: "LAJA" },
  { ComunaId: 132, Nombre: "LAMPA" },
  { ComunaId: 133, Nombre: "LANCO" },
  { ComunaId: 134, Nombre: "LAS CABRAS" },
  { ComunaId: 135, Nombre: "LAS CONDES" },
  { ComunaId: 136, Nombre: "LAUTARO" },
  { ComunaId: 137, Nombre: "LEBU" },
  { ComunaId: 138, Nombre: "LICANTEN" },
  { ComunaId: 139, Nombre: "LIMACHE" },
  { ComunaId: 140, Nombre: "LINARES" },
  { ComunaId: 141, Nombre: "LITUECHE" },
  { ComunaId: 142, Nombre: "LLANQUIHUE" },
  { ComunaId: 143, Nombre: "LLAY-LLAY" },
  { ComunaId: 144, Nombre: "LO BARNECHEA" },
  { ComunaId: 145, Nombre: "LO ESPEJO" },
  { ComunaId: 146, Nombre: "LO PRADO" },
  { ComunaId: 147, Nombre: "LOLOL" },
  { ComunaId: 148, Nombre: "LONCOCHE" },
  { ComunaId: 149, Nombre: "LONGAVI" },
  { ComunaId: 150, Nombre: "LONQUIMAY" },
  { ComunaId: 151, Nombre: "LOS ALAMOS" },
  { ComunaId: 152, Nombre: "LOS ANDES" },
  { ComunaId: 153, Nombre: "LOS ANGELES" },
  { ComunaId: 154, Nombre: "LOS LAGOS" },
  { ComunaId: 155, Nombre: "LOS MUERMOS" },
  { ComunaId: 156, Nombre: "LOS SAUCES" },
  { ComunaId: 157, Nombre: "LOS VILOS" },
  { ComunaId: 158, Nombre: "LOTA" },
  { ComunaId: 159, Nombre: "LUMACO" },
  { ComunaId: 160, Nombre: "MACHALI" },
  { ComunaId: 161, Nombre: "MACUL" },
  { ComunaId: 162, Nombre: "MAFIL" },
  { ComunaId: 163, Nombre: "MAIPU" },
  { ComunaId: 164, Nombre: "MALLOA" },
  { ComunaId: 165, Nombre: "MARCHIGUE" },
  { ComunaId: 166, Nombre: "MARIA ELENA" },
  { ComunaId: 167, Nombre: "MARIA PINTO" },
  { ComunaId: 168, Nombre: "MARIQUINA" },
  { ComunaId: 169, Nombre: "MAULE" },
  { ComunaId: 170, Nombre: "MAULLIN" },
  { ComunaId: 171, Nombre: "MEJILLONES" },
  { ComunaId: 172, Nombre: "MELIPEUCO" },
  { ComunaId: 173, Nombre: "MELIPILLA" },
  { ComunaId: 174, Nombre: "MOLINA" },
  { ComunaId: 175, Nombre: "MONTE PATRIA" },
  { ComunaId: 176, Nombre: "MULCHEN" },
  { ComunaId: 177, Nombre: "NACIMIENTO" },
  { ComunaId: 178, Nombre: "NANCAGUA" },
  { ComunaId: 179, Nombre: "NATALES" },
  { ComunaId: 180, Nombre: "NAVIDAD" },
  { ComunaId: 181, Nombre: "NEGRETE" },
  { ComunaId: 182, Nombre: "NINHUE" },
  { ComunaId: 183, Nombre: "NIQUEN" },
  { ComunaId: 184, Nombre: "NOGALES" },
  { ComunaId: 185, Nombre: "NUEVA IMPERIAL" },
  { ComunaId: 186, Nombre: "NUNOA" },
  { ComunaId: 187, Nombre: "OHIGGINS" },
  { ComunaId: 188, Nombre: "OLIVAR" },
  { ComunaId: 189, Nombre: "OLLAGUE" },
  { ComunaId: 190, Nombre: "OLMUE" },
  { ComunaId: 191, Nombre: "OSORNO" },
  { ComunaId: 192, Nombre: "OVALLE" },
  { ComunaId: 193, Nombre: "PADRE HURTADO" },
  { ComunaId: 194, Nombre: "PADRE LAS CASAS" },
  { ComunaId: 195, Nombre: "PAIHUANO" },
  { ComunaId: 196, Nombre: "PAILLACO" },
  { ComunaId: 197, Nombre: "PAINE" },
  { ComunaId: 198, Nombre: "PALENA" },
  { ComunaId: 199, Nombre: "PALMILLA" },
  { ComunaId: 200, Nombre: "PANGUIPULLI" },
  { ComunaId: 201, Nombre: "PANQUEHUE" },
  { ComunaId: 202, Nombre: "PAPUDO" },
  { ComunaId: 203, Nombre: "PAREDONES" },
  { ComunaId: 204, Nombre: "PARRAL" },
  { ComunaId: 205, Nombre: "PEDRO AGUIRRE CERDA" },
  { ComunaId: 206, Nombre: "PELARCO" },
  { ComunaId: 207, Nombre: "PELLUHUE" },
  { ComunaId: 208, Nombre: "PEMUCO" },
  { ComunaId: 209, Nombre: "PENAFLOR" },
  { ComunaId: 210, Nombre: "PENALOLEN" },
  { ComunaId: 211, Nombre: "PENCAHUE" },
  { ComunaId: 212, Nombre: "PENCO" },
  { ComunaId: 213, Nombre: "PERALILLO" },
  { ComunaId: 214, Nombre: "PERQUENCO" },
  { ComunaId: 215, Nombre: "PETORCA" },
  { ComunaId: 216, Nombre: "PEUMO" },
  { ComunaId: 217, Nombre: "PICA" },
  { ComunaId: 218, Nombre: "PICHIDEGUA" },
  { ComunaId: 219, Nombre: "PICHILEMU" },
  { ComunaId: 220, Nombre: "PINTO" },
  { ComunaId: 221, Nombre: "PIRQUE" },
  { ComunaId: 222, Nombre: "PITRUFQUEN" },
  { ComunaId: 223, Nombre: "PLACILLA" },
  { ComunaId: 224, Nombre: "PORTEZUELO" },
  { ComunaId: 225, Nombre: "PORVENIR" },
  { ComunaId: 226, Nombre: "POZO ALMONTE" },
  { ComunaId: 227, Nombre: "PRIMAVERA" },
  { ComunaId: 228, Nombre: "PROVIDENCIA" },
  { ComunaId: 229, Nombre: "PUCHUNCAVI" },
  { ComunaId: 230, Nombre: "PUCON" },
  { ComunaId: 231, Nombre: "PUDAHUEL" },
  { ComunaId: 232, Nombre: "PUENTE ALTO" },
  { ComunaId: 233, Nombre: "PUERTO MONTT" },
  { ComunaId: 234, Nombre: "PUERTO OCTAY" },
  { ComunaId: 235, Nombre: "PUERTO VARAS" },
  { ComunaId: 236, Nombre: "PUMANQUE" },
  { ComunaId: 237, Nombre: "PUNITAQUI" },
  { ComunaId: 238, Nombre: "PUNTA ARENAS" },
  { ComunaId: 239, Nombre: "PUQUELDON" },
  { ComunaId: 240, Nombre: "PUREN" },
  { ComunaId: 241, Nombre: "PURRANQUE" },
  { ComunaId: 242, Nombre: "PUTAENDO" },
  { ComunaId: 243, Nombre: "PUTRE" },
  { ComunaId: 244, Nombre: "PUYEHUE" },
  { ComunaId: 245, Nombre: "QUEILEN" },
  { ComunaId: 246, Nombre: "QUELLON" },
  { ComunaId: 247, Nombre: "QUEMCHI" },
  { ComunaId: 248, Nombre: "QUILACO" },
  { ComunaId: 249, Nombre: "QUILICURA" },
  { ComunaId: 250, Nombre: "QUILLECO" },
  { ComunaId: 251, Nombre: "QUILLON" },
  { ComunaId: 252, Nombre: "QUILLOTA" },
  { ComunaId: 253, Nombre: "QUILPUE" },
  { ComunaId: 254, Nombre: "QUINCHAO" },
  { ComunaId: 255, Nombre: "QUINTA DE TILCOCO" },
  { ComunaId: 256, Nombre: "QUINTA NORMAL" },
  { ComunaId: 257, Nombre: "QUINTERO" },
  { ComunaId: 258, Nombre: "QUIRIHUE" },
  { ComunaId: 259, Nombre: "RANCAGUA" },
  { ComunaId: 260, Nombre: "RANQUIL" },
  { ComunaId: 261, Nombre: "RAUCO" },
  { ComunaId: 262, Nombre: "RECOLETA" },
  { ComunaId: 263, Nombre: "RENAICO" },
  { ComunaId: 264, Nombre: "RENCA" },
  { ComunaId: 265, Nombre: "RENGO" },
  { ComunaId: 266, Nombre: "REQUINOA" },
  { ComunaId: 267, Nombre: "RETIRO" },
  { ComunaId: 268, Nombre: "RINCONADA" },
  { ComunaId: 269, Nombre: "RIO BUENO" },
  { ComunaId: 270, Nombre: "RIO CLARO" },
  { ComunaId: 271, Nombre: "RIO HURTADO" },
  { ComunaId: 272, Nombre: "RIO IBANEZ" },
  { ComunaId: 273, Nombre: "RIO NEGRO" },
  { ComunaId: 274, Nombre: "RIO VERDE" },
  { ComunaId: 275, Nombre: "ROMERAL" },
  { ComunaId: 276, Nombre: "SAAVEDRA" },
  { ComunaId: 277, Nombre: "SAGRADA FAMILIA" },
  { ComunaId: 278, Nombre: "SALAMANCA" },
  { ComunaId: 279, Nombre: "SAN ANTONIO" },
  { ComunaId: 280, Nombre: "SAN BERNARDO" },
  { ComunaId: 281, Nombre: "SAN CARLOS" },
  { ComunaId: 282, Nombre: "SAN CLEMENTE" },
  { ComunaId: 283, Nombre: "SAN ESTEBAN" },
  { ComunaId: 284, Nombre: "SAN FABIAN" },
  { ComunaId: 285, Nombre: "SAN FELIPE" },
  { ComunaId: 286, Nombre: "SAN FERNANDO" },
  { ComunaId: 287, Nombre: "SAN FRANCISCO DE MOSTAZAL" },
  { ComunaId: 288, Nombre: "SAN GREGORIO" },
  { ComunaId: 289, Nombre: "SAN IGNACIO" },
  { ComunaId: 290, Nombre: "SAN JAVIER" },
  { ComunaId: 291, Nombre: "SAN JOAQUIN" },
  { ComunaId: 292, Nombre: "SAN JOSE DE MAIPO" },
  { ComunaId: 293, Nombre: "SAN JUAN DE LA COSTA" },
  { ComunaId: 294, Nombre: "SAN MIGUEL" },
  { ComunaId: 295, Nombre: "SAN NICOLAS" },
  { ComunaId: 296, Nombre: "SAN PABLO" },
  { ComunaId: 297, Nombre: "SAN PEDRO" },
  { ComunaId: 298, Nombre: "SAN PEDRO DE ATACAMA" },
  { ComunaId: 299, Nombre: "SAN PEDRO DE LA PAZ" },
  { ComunaId: 300, Nombre: "SAN RAFAEL" },
  { ComunaId: 301, Nombre: "SAN RAMON" },
  { ComunaId: 302, Nombre: "SAN ROSENDO" },
  { ComunaId: 303, Nombre: "SAN VICENTE" },
  { ComunaId: 304, Nombre: "SANTA BARBARA" },
  { ComunaId: 305, Nombre: "SANTA CRUZ" },
  { ComunaId: 306, Nombre: "SANTA JUANA" },
  { ComunaId: 307, Nombre: "SANTA MARIA" },
  { ComunaId: 308, Nombre: "SANTIAGO" },
  { ComunaId: 309, Nombre: "SANTIAGO OESTE" },
  { ComunaId: 310, Nombre: "SANTIAGO SUR" },
  { ComunaId: 311, Nombre: "SANTO DOMINGO" },
  { ComunaId: 312, Nombre: "SIERRA GORDA" },
  { ComunaId: 313, Nombre: "TALAGANTE" },
  { ComunaId: 314, Nombre: "TALCA" },
  { ComunaId: 315, Nombre: "TALCAHUANO" },
  { ComunaId: 316, Nombre: "TALTAL" },
  { ComunaId: 317, Nombre: "TEMUCO" },
  { ComunaId: 318, Nombre: "TENO" },
  { ComunaId: 319, Nombre: "TEODORO SCHMIDT" },
  { ComunaId: 320, Nombre: "TIERRA AMARILLA" },
  { ComunaId: 321, Nombre: "TIL-TIL" },
  { ComunaId: 322, Nombre: "TIMAUKEL" },
  { ComunaId: 323, Nombre: "TIRUA" },
  { ComunaId: 324, Nombre: "TOCOPILLA" },
  { ComunaId: 325, Nombre: "TOLTEN" },
  { ComunaId: 326, Nombre: "TOME" },
  { ComunaId: 327, Nombre: "TORRES DEL PAINE" },
  { ComunaId: 328, Nombre: "TORTEL" },
  { ComunaId: 329, Nombre: "TRAIGUEN" },
  { ComunaId: 330, Nombre: "TREHUACO" },
  { ComunaId: 331, Nombre: "TUCAPEL" },
  { ComunaId: 332, Nombre: "VALDIVIA" },
  { ComunaId: 333, Nombre: "VALLENAR" },
  { ComunaId: 334, Nombre: "VALPARAISO" },
  { ComunaId: 335, Nombre: "VICHUQUEN" },
  { ComunaId: 336, Nombre: "VICTORIA" },
  { ComunaId: 337, Nombre: "VICUNA" },
  { ComunaId: 338, Nombre: "VILCUN" },
  { ComunaId: 339, Nombre: "VILLA ALEGRE" },
  { ComunaId: 340, Nombre: "VILLA ALEMANA" },
  { ComunaId: 341, Nombre: "VILLARRICA" },
  { ComunaId: 342, Nombre: "VINA DEL MAR" },
  { ComunaId: 343, Nombre: "VITACURA" },
  { ComunaId: 344, Nombre: "YERBAS BUENAS" },
  { ComunaId: 345, Nombre: "YUMBEL" },
  { ComunaId: 346, Nombre: "YUNGAY" },
  { ComunaId: 347, Nombre: "ZAPALLAR" }
];